baseURL = 'https://www.luisdesousa.com/'
languageCode = "en-us"
title = "Luis de Sousa"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

[params]
    author = "Luis de Sousa"
    description = "Dreaming and creating."

[params.homeInfoParams]
    Title = "Hi there! ğŸ‘‹"
    Content = "Welcome to my blog ğŸ“âœ¨, a collection of my thoughts ğŸ’­, interests ğŸŒŸ, and ideas ğŸ’¡!"

[params.editPost]
    URL = "https://github.com/luisdza/luis-de-sousa-dot-com/tree/main/content"
    Text = "Edit" # edit text
    appendFilePath = true # to append file path to Edit link

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[taxonomies]
    category = "categories"
    tag = "tags"

[minify]
  minifyOutput = true
  disableXML = true