baseURL = 'https://www.luisdesousa.com/'
languageCode = "en-us"
title = "Luis de Sousa"
theme = "PaperMod"
enableRobotsTXT = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

[params]
    author = "Luis de Sousa"
    description = "Dreaming and creating."

[params.homeInfoParams]
    Title = "Hi there! ğŸ‘‹"
    Content = """
        ğŸ™‹â€â™‚ï¸ I'm Luis de Sousa, ğŸ‡¿ğŸ‡¦ based in Johannesburg, South Africa.
        ğŸ“ This blog is a collection of my ğŸ’­ thoughts, ğŸŒŸ interests, and ğŸ’¡ ideas.
    """

[[params.socialIcons]]
    name = "linkedin"
    url = 'https://www.linkedin.com/in/luisdza'

[[params.socialIcons]]
    name = "github"
    url = 'https://www.github.com/luisdza'

[[params.socialIcons]]
    name = "twitter"
    url = 'https://www.twitter.com/luis_de_sousa'

[[params.socialIcons]]
    name = "mastodon"
    url = 'https://fosstodon.org/@Luisd'

[[params.socialIcons]]
    name = "RSS"
    url = 'index.xml'

[params.editPost]
    URL = "https://github.com/luisdza/luis-de-sousa-dot-com/tree/main/content"
    Text = "Edit" # edit text
    appendFilePath = true # to append file path to Edit link

[menu]
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[taxonomies]
    category = "categories"
    tag = "tags"

[minify]
  minifyOutput = true
  disableXML = true